services:
  app:
    # Сервер Node.js
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/node/app
    ports:
      #  - "3001:3000"


      - "9229:9229"
    networks:
      - my-network # Використовуємо мережу my-network

  nginx:
    # Сервер Nginx
    image: nginx:latest # Використовуємо офіційний образ Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80" # Порт для доступу до Nginx ззовні
    networks:
      - my-network # Використовуємо ту ж мережу

networks:
  my-network:
