services:
    app:
        # Сервер Node.js
        build:
            context: . # Контекст збірки, де розташовано Dockerfile
        ports:
            - "3001:3000" # Порт для доступу до сервера ззовні
        networks:
            - my-network # Використовуємо мережу my-network

    nginx:
        # Сервер Nginx
        image: nginx:latest # Використовуємо офіційний образ Nginx
        volumes:
            #- "/d/College/Client-server architecture/praktychna_1_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
            #- "/d/College/Client-server architecture/praktychna_1_docker/html:/usr/share/nginx/html:ro"
            #- "/d/College/Client-server architecture/praktychna_1_docker/static:/usr/share/nginx/static:ro"
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./static:/usr/share/nginx/static:ro
            - ./html:/usr/share/nginx/html:ro
        ports:
            - "80:80" # Порт для доступу до Nginx ззовні
        networks:
            - my-network # Використовуємо ту ж мережу

networks:
    my-network:
