services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - app-network
            - app-mongo-network
            - app-postgres-network
        ports:
            - ${DEV_APP_PORT:-3000}
        volumes:
            - .:/srv/node/app
        environment:
            - NODE_ENV=${NODE_ENV:-development}
            - APP_HOST=${APP_HOST:-0.0.0.0}
            - APP_PORT=${APP_PORT:-3000}
            - REBUILD_PRISMA_CLIENT=${REBUILD_PRISMA_CLIENT:-}
            - APP_PG_DATABASE_URL=${APP_PG_DATABASE_URL}
            - APP_MONGO_DATABASE_URL=${APP_MONGO_DATABASE_URL}
        depends_on:
            - postgres
            - mongo

    postgres:
        image: postgres:latest
        networks:
            - app-postgres-network
        ports:
            - "5432:5432" # Вказати порт для зовнішнього доступу
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    mongo:
        image: mongo:latest
        networks:
            - app-mongo-network
        ports:
            - "27017:27017" # Вказати порт для зовнішнього доступу
        volumes:
            - mongo-data:/data/db

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        networks:
            - app-network
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./static:/usr/share/nginx/static:ro
            - ./html:/usr/share/nginx/html:ro
        depends_on:
            - app

networks:
    app-network:
        driver: bridge

    app-mongo-network:
        driver: bridge

    app-postgres-network:
        driver: bridge

volumes:
    postgres-data:
    mongo-data:
